# Generated by Django 2.2 on 2021-10-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(null=True, related_name='cart_item', to='ecomm_app.Item'),
        ),
    ]
