# Generated by Django 2.2 on 2021-10-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0005_auto_20211017_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
