# Generated by Django 2.2 on 2021-10-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0008_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
