# Generated by Django 2.2 on 2021-11-13 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0011_auto_20211113_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='User',
        ),
        migrations.AddField(
            model_name='star',
            name='review',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='ecomm_app.Review'),
            preserve_default=False,
        ),
    ]
