# Generated by Django 2.2 on 2021-11-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0012_auto_20211113_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
